### ISSUE TITLE
[Feature Request] Default config file name

### ISSUE THREAD

**Issue by ColeWalker-Drizly** [napisani/procmux#23]
Searching for a file named `procmux-config.yaml` in the current directory instead of requiring the `--config` option every time that you run the program would be very convenient.

**Comment by napisani** [comment]
great idea!
added a PR, we'll get this released shortly
https://github.com/napisani/procmux/pull/24

**Comment by napisani** [comment]
@ColeWalker-Drizly version 1.0.10 has been released to pypi and brew with this new feature :) 

Thanks again for the suggestion!
